mosip.resident.client.secret=M6XH2paYigGOUmoU
mosip.kernel.tokenid.uin.salt=r1jMqKqQXs7AtKs4
mosip.kernel.tokenid.partnercode.salt=nQWuR5lC3TJMlVPc
resident.websub.authtype.status.secret=EPpZWwqJqPdm9gV0
resident.websub.auth.transaction.status.secret=jlu3SBCHbWdHwWQ0
resident.websub.credential.status.update.secret=ORKfJQAh3naj0vHk
spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
