[kafkaHub.config]
# Flag to check whether to enable/disable security
SECURITY_ON = true

# Server ID is is used to uniquely identify each server
# Each server must have a unique ID
SERVER_ID = "server-1"

# IP and Port of the Kafka bootstrap node
KAFKA_BOOTSTRAP_NODE = "kafka.${kafka.profile}:${kafka.port}"

# Kafka topic which will get notified for websub topic registration/deregistration
# All the hubs must be pointed to the same Kafka topic to notify websub topic registration/deregistration
REGISTERED_WEBSUB_TOPICS_TOPIC = "registered-websub-topics"

# Kafka topic which stores consolidated websub topics for the hub
CONSOLIDATED_WEBSUB_TOPICS_TOPIC = "consolidated-websub-topics"

# Kafka topic which will get notified for websub subscription/unsubscription
# All the hubs must be pointed to the same Kafka topic to notify websub subscription/unsubscription
WEBSUB_SUBSCRIBERS_TOPIC = "registered-websub-subscribers"

# Kafka topic which is stores consolidated websub subscribers for this server
CONSOLIDATED_WEBSUB_SUBSCRIBERS_TOPIC = "consolidated-websub-subscribers"

# The interval in which Kafka consumers wait for new messages
POLLING_INTERVAL = 10.0

# The period in which Kafka close method waits to complete
GRACEFUL_CLOSE_PERIOD = 5.0

# The port that is used to start the hub
HUB_PORT = 9191

# The period between retry requests
MESSAGE_DELIVERY_RETRY_INTERVAL = 3.0

# The maximum retry count
MESSAGE_DELIVERY_COUNT = 3

# The maximum retry count
KAFKA_CONSUMER_MAX_POLL_RECORDS = 1

# The message delivery timeout
MESSAGE_DELIVERY_TIMEOUT = 60.0

# The base URL of IDP
MOSIP_AUTH_BASE_URL = "${mosip.kernel.authmanager.url}/v1/authmanager"


# The token validation URL of IDP
MOSIP_AUTH_VALIDATE_TOKEN_URL = "/authorize/admin/validateToken"

[ballerina.http.accessLogConfig]
# Enable printing access logs in console
console = true              # Default is false

[ballerina.http.traceLogAdvancedConfig]
# Enable printing trace logs in console
console = true              # Default is false

#Encryption key that will be used to encrypt / decrypt the hub secret
#hub_secret_encryption_key = "${hub-secret-encryption-key}"
